spring:
  application:
    name: todo-app
  datasource:
    url: jdbc:postgres://app_uenm_user:hbD2aWjHLqCs0hFtPn5vpq5Pu2GZFDQm@dpg-cnesr67sc6pc73cpe2k0-a/app_uenm
    password: hbD2aWjHLqCs0hFtPn5vpq5Pu2GZFDQm
    username: rean
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
